### ISSUE TITLE
REAL implementation crashes in eclipse

### ISSUE THREAD

**Issue by juli1** [OpenAADL/osate2-ocarina#10]
When opening the adiru model in OSATE, I got the following error.

An internal error occurred during: "calculating highlighting".
org.osate.aadl2.impl.DefaultAnnexSubclauseImpl cannot be cast to org.osate.ocarina.real.xtext.annex.REALAnnexBlock

**Comment by yoogx** [comment]
REAL was implemented as an annex language a while back, contributed by Phil Alldredge. The full language has never been implemented, leading to a few errors. I understand management of annexes has been updated recently. 

My suggestion would be simply to deactivate this part of the plug-in, if not remove it from the project as it will be superseded by the Constraint annex, and is currently replaced by resolute.

Lutz or Julien, can you proceed with this ? I think you have a better understanding of eclipse machinery to perform this.

Thanks
