### ISSUE TITLE
Code generation with Ocarina crashes when using the Deployment property set

### ISSUE THREAD

**Issue by paolo-crisafulli** [OpenAADL/osate2-ocarina#14]
Using:
- Osate 2.3.1
- Ocarina 2017.1 (https://github.com/OpenAADL/ocarina/releases/tag/v2017.1)

In a fresh AADL project, include and open the attached AADL model file (renamed as txt): [this-crashes-ocarina-plugin.txt](https://github.com/OpenAADL/osate2-ocarina/files/1708011/this-crashes-ocarina-plugin.txt)

In the Outline view, right-click on mysystem.impl, then click Ocarina > Generate PolyORB-Hi-C code

You will get:
An internal error occurred during: "Running Ocarina".
Unable to get IResource for Resource: org.eclipse.xtext.resource.DerivedStateAwareResource@c72a4f5 uri='platform:/plugin/org.osate.ocarina.aadlcontribution/resources/properties/deployment.aadl'

**Comment by yoogx** [comment]
Thanks for the pointer. OSATE recently changed the way default property sets are fetched. I'll propose a patch shortly

**Comment by paolo-crisafulli** [comment]
That would be very helpful, thank you.

**Comment by paolo-crisafulli** [comment]
Hi @yoogx , any news about the patch?
Our team would be very interested, and I can provide feedback if it may help.

**Comment by yoogx** [comment]
Here is a work-around for the moment: check-out the source code of the plug-in in your workspace.

You'll notice that in the console:

/Users/hugues/local/ocarina/bin/ocarina -aadlv2 -g polyorb_hi_c -r blinky.impl -o /Users/hugues/git/osate2-ocarina/org.osate.ocarina.aadlcontribution/resources/properties /Users/hugues/git/AADLib/examples/stm32discovery_ada/stm32discovery_ada.aadl /Users/hugues/git/osate2-ocarina/org.osate.ocarina.aadlcontribution/resources/properties/deployment.aadl

I'm working on a patch for the next release

**Comment by yoogx** [comment]
The patch is now done, it will be available as part of OSATE 2.3.2 release, you have a work around using 2.3.1 as reported below. Note I strongly recommend you use Ocarina on Linux. Being a code generator, it works better on this OS. I do not develop on Windows.

Also, I suggest you review existing examples, e.g. from AADLib and PolyORB-HI/C repositories.

**Comment by paolo-crisafulli** [comment]
Thank you very much.
I see Osate 2.3.2 is out, so I'll check directly with that release.

**Comment by paolo-crisafulli** [comment]
Works fine, thank you!

**Comment by yoogx** [comment]
Good to know. Note I strongly recommend you experiment first with the provided examples either in AADLib or PolyORB-HI/C. I'm working on the documentation right now, but it won't be available before mid-2018. It is likely you'll use modelling patterns that are not consistent with the expected domain of usage of the tool
