### ISSUE TITLE
Code generation problem with OSATE and Ocarina plugin

### ISSUE THREAD

**Issue by phamhoanganhbk** [OpenAADL/osate2-ocarina#15]
Hi @yoogx ,

I am using the OSATE (version osate2-2.3.6-vfinal-linux.gtk.x86_64)
and Ocarina (version ocarina-2017.1-suite-linux-x86_64-20170204), I used the version "suite" because i have tried many times to install following the link https://ocarina.readthedocs.io/en/latest/installation.html, but I still haven't succeeded. 

Then I modified a path under OSATE Preferences/Ocarina like `/home/anhph/ocarina-2017.1-suite-linux-x86_64-20170204/bin` (I'm not sure if that is correct with the version suite of ocarina).
After that, I have used the example "adiru" following the path `ocarina-2017.1-suite-linux-x86_64-20170204/examples` to generate code. I have always this error :
`An internal error occurred during: "Running Ocarina".Unable to get IResource for Resource: org.osate.xtext.aadl2.resource.NoCacheDerivedStateAwareResource@2ae9c6e uri='platform:/plugin/org.osate.aadl2.errormodel.contrib/resources/properties/EMV2.aadl'`

Could you give me some advice to fix it, please? 
Many thanks,

**Comment by yoogx** [comment]
This is a followup to #14 , will use this one to trace progress
