### ISSUE TITLE
how to install ocarina in osate?

### ISSUE THREAD

**Issue by Blissqiu** [OpenAADL/osate2-ocarina#18]
I saw on the website that the latest osate integrated the ocarina, but when I used it, there was a problem  (path to ocarina not to set up). The website of install new software on the official website could not be accessed. Is there any foolproof way to install it?Let me use the function of the ocarina in osate on Windows.

**Comment by yoogx** [comment]
You need to install separately Ocarina on your machine. The latest available release is there: https://github.com/OpenAADL/ocarina/releases

**Comment by ghostezhouxingyu** [comment]
> You need to install separately Ocarina on your machine. The latest available release is there: https://github.com/OpenAADL/ocarina/releases

which one should I download for windows

**Comment by yoogx** [comment]
There are no recent OSATE binaries provided. It is recommended you build your own.
Windows is not a primary target. So I would advise you use Linux instead
