### ISSUE TITLE
osate2-ocarina

### ISSUE THREAD

**Issue by Zengwenlin** [OpenAADL/osate2-ocarina#21]
Hi all,
I'm new but very interested on ocate2-ocarina project ,I met some issue when trying to install osate2-ocarina plug-in in Osate2-2.7.0-vfinal-win32.win32.x86_64 in my win10 PC. 
 I installed the plugin from "Install additional OSATE components ",  a warning happened during the installation. Bellow is the warning info: "You are installing software that contains unsigned content. The authenticity or validaity of this software cannot be established . Do you want to continue with the installation?" I then chose "install anyway" to finished the installation.
But I cannot fine any ocarina bin directory when trying to configure ocarina in eclipse preference.
So do I install ocarina successfully?
and Do i need to install ocarina before installing osate2-ocarina plugin ?

Thanks for you help in advance.

**Comment by yoogx** [comment]
You need to install Ocarina and its plugin. Then configure the plugin to point to ocarina bin/ directory.
