### ISSUE TITLE
Installation Failed : make: *** [all-recursive] Error 1

### ISSUE THREAD

**Issue by nikhilakn** [OpenAADL/osate2-ocarina#22]
I had tried to install ocarina using the instructions given in the link :https://github.com/openaadl/ocarina-build.

But I got the following error.

Guessing OS
linux
OS:        Ubuntu 16.04.5 LTS x86_64
Compiler:  GNATMAKE 4.9.3
autoconf:  autoconf (GNU Autoconf) 2.69
automake:  automake (GNU automake) 1.15
[2020-07-23-13:22] Checkout the Ocarina sources                                                                        [PASSED]
[2020-07-23-13:22] Fetching runtimes 'polyorb-hi-ada polyorb-hi-c aadlib'                                              [PASSED]
[2020-07-23-13:22] Reconfiguring (Ocarina)                                                                             [PASSED]
[2020-07-23-13:22] First configure (Ocarina)                                                                           [PASSED]
[2020-07-23-13:23] Doing 'make' (Ocarina)[2020-07-23-13:23] Doing 'make' (Ocarina)                                                                              [FAILED]
Making all in support
make[1]: Entering directory '/home/selab/ocarina-build/ocarina/support'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/selab/ocarina-build/ocarina/support'
Making all in tools
make[1]: Entering directory '/home/selab/ocarina-build/ocarina/tools'
make[2]: Entering directory '/home/selab/ocarina-build/ocarina/tools'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/selab/ocarina-build/ocarina/tools'
make[1]: Leaving directory '/home/selab/ocarina-build/ocarina/tools'
Making all in projects
make[1]: Entering directory '/home/selab/ocarina-build/ocarina/projects'
Makefile:623: target 'gnatcheck' doesn't match the target pattern
Makefile:629: target 'gnatmetric' doesn't match the target pattern
touch ../src/core/objects-stamp
touch ../src/config/objects-stamp
touch ../src/frontends/objects-stamp
touch ../src/backends/objects-stamp
touch ../src/transfo/objects-stamp
touch ../src/main/objects-stamp
touch ../src/python/objects-stamp
touch ../src/core/libs-stamp
touch ../src/frontends/libs-stamp
touch ../src/backends/libs-stamp
touch ../src/transfo/libs-stamp
touch ../src/config/libs-stamp
touch ../src/main/libs-stamp
touch ../src/python/libs-stamp
Creating directory: ../src/core/objects
mkdir -p ../src/core/objects
Creating directory: ../src/config/objects
mkdir -p ../src/config/objects
Creating directory: ../src/frontends/objects
mkdir -p ../src/frontends/objects
Creating directory: ../src/backends/objects
mkdir -p ../src/backends/objects
Creating directory: ../src/transfo/objects
mkdir -p ../src/transfo/objects
Creating directory: ../src/main/objects
mkdir -p ../src/main/objects
Creating directory: ../src/python/objects
mkdir -p ../src/python/objects
Creating directory: ../src/core/libs
mkdir -p ../src/core/libs
Creating directory: ../src/frontends/libs
mkdir -p ../src/frontends/libs
Creating directory: ../src/backends/libs
mkdir -p ../src/backends/libs
Creating directory: ../src/transfo/libs
mkdir -p ../src/transfo/libs
Creating directory: ../src/config/libs
mkdir -p ../src/config/libs
Creating directory: ../src/main/libs
mkdir -p ../src/main/libs
Creating directory: ../src/python/libs
mkdir -p ../src/python/libs
if [ -f ../tools/mknodes/mknodes.gpr ]; then \
   mkdir -p ../tools/mknodes/objects; \
    \
     /usr/bin/gprbuild -P ../tools/mknodes/mknodes.gpr \
     -XABS_SRC_DIR="/home/selab/ocarina-build/ocarina/src" \
     -XABS_BUILD_DIR="/home/selab/ocarina-build/ocarina/src" \
     -aP../projects -aP../projects \
     -XBUILD=release ; \
fi
gnatgcc -c -O2 -gnat12 -gnata -gnaty -gnatyu -gnatys -gnatpn mknodes.adb
/home/selab/ocarina-build/ocarina/src/../projects/restrictions.adc:30:22: invalid restriction identifier "No_Fixed_Io"
/home/selab/ocarina-build/ocarina/src/../projects/restrictions.adc:64:22: invalid restriction identifier "No_Implicit_Task_Allocations"
/home/selab/ocarina-build/ocarina/src/../projects/restrictions.adc:65:22: invalid restriction identifier "No_Implicit_Protected_Object_Allocations"
/home/selab/ocarina-build/ocarina/src/../projects/restrictions.adc:75:22: invalid restriction identifier "No_Task_At_Interrupt_Priority"
/home/selab/ocarina-build/ocarina/src/../projects/restrictions.adc:80:22: invalid restriction identifier "Pure_Barriers"
gprbuild: *** compilation phase failed
Makefile:667: recipe for target 'build-mknodes' failed
make[1]: *** [build-mknodes] Error 4
make[1]: Leaving directory '/home/selab/ocarina-build/ocarina/projects'
Makefile:421: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Could you give me some advice to fix this, please?

Thanks

**Comment by yoogx** [comment]
Your version of GNAT is really old: Compiler: GNATMAKE 4.9.3
You must update to something more recent, either install GNAT Community Edition 2020, or update to a different GCC in your base Ubuntu

**Comment by nikhilakn** [comment]
I had upgrade GCC to 10 in my base ubuntu. Still, the same issue is there :-(

**Comment by yoogx** [comment]
Clean the whole build dir, you may still be using the old compiler. U have ocarina compiled with gcc 10 on debian

Le 4 août 2020 à 07:34, nikhilakn <notifications@github.com> a écrit :

﻿

I had upgrade GCC to 10 in my base ubuntu. Still, the same issue is there :-(
