### ISSUE TITLE
Update help page

### ISSUE THREAD

**Issue by dzid26** [OpenAADL/osate2-ocarina#24]
This [statement ](http://www.openaadl.org/osate-ocarina.html)not entirely true for Osate >= 2.7:

> Since the release of OSATE 2.0.9, this plugin is now part of the distribution, there is no specific action required to install it.

Should be updated based on Osate [release notes](https://osate.org/osate-releases.html):
> The Ocarina Connector plugin is now a separate component that can be installed via Help -> Install Additional OSATE Components.

**Comment by yoogx** [comment]
Thanks for the heads up
